from __future__ import annotations

import hashlib
import io
import json
import re
import zipfile


def _safe_key(name: str, fallback: str) -> str:
    value = re.sub(r"[^0-9A-Za-z_-]+", "-", (name or "").strip()).strip("-")
    return value or fallback


def build_terraform_pack(workloads, target_clusters) -> bytes:
    """Build a non-destructive Terraform planning pack.

    VM resources are gated behind enable_vm_creation=false by default. The
    export is intended for IaC review and approved rebuild/greenfield cases,
    not as a substitute for Nutanix Move migration execution.
    """
    workload_map = {}
    for index, w in enumerate(workloads, start=1):
        key = _safe_key(w.name, f"workload-{index}")
        if key in workload_map:
            key = f"{key}-{w.id}"
        workload_map[key] = {
            "name": w.name,
            "wave": w.wave_number,
            "vcpu": int(w.cpu or 1),
            "memory_size_bytes": int(float(w.memory_gb or 1) * 1024 * 1024 * 1024),
            "storage_gb": float(w.storage_gb or 0),
            "target_network": w.target_network or "",
            "app_group": w.app_group or "Ungrouped",
            "criticality": w.criticality or "Medium",
        }

    cluster_map = {
        _safe_key(c.name, f"cluster-{c.id}"): {
            "name": c.name,
            "ext_id": c.prism_ext_id or "",
            "enabled": bool(c.enabled),
        }
        for c in target_clusters
    }

    versions_tf = '''terraform {
  required_version = ">= 1.6.0"

  required_providers {
    nutanix = {
      source  = "nutanix/nutanix"
      version = ">= 2.4.2, < 3.0.0"
    }
  }
}
'''

    provider_tf = '''provider "nutanix" {
  endpoint = var.nutanix_endpoint
  api_key  = var.nutanix_api_key
  port     = var.nutanix_port
  insecure = var.nutanix_insecure
}
'''

    variables_tf = '''variable "nutanix_endpoint" {
  description = "Prism Central hostname or IP address."
  type        = string
}

variable "nutanix_api_key" {
  description = "Prism Central API key. Supply via TF_VAR_nutanix_api_key; never commit it."
  type        = string
  sensitive   = true
}

variable "nutanix_port" {
  description = "Prism Central API port."
  type        = number
  default     = 9440
}

variable "nutanix_insecure" {
  description = "Disable TLS verification. Keep false outside controlled development."
  type        = bool
  default     = false
}

variable "cluster_ext_id" {
  description = "Authorized target AHV cluster extId."
  type        = string
}

variable "subnet_ext_ids" {
  description = "Map of Migration Factory target-network names to Prism subnet extIds."
  type        = map(string)
  default     = {}
}

variable "enable_vm_creation" {
  description = "Safety gate. False by default because Move migrations should not be replaced by blind Terraform VM recreation."
  type        = bool
  default     = false
}
'''

    locals_tf = "locals {\n  workloads = " + json.dumps(workload_map, indent=2) + "\n}\n"

    planned_vms_tf = '''# SAFETY: VM creation is disabled by default.
#
# Migration Factory primarily plans VMware -> AHV migrations performed with
# Nutanix Move. These resources are an IaC review scaffold for greenfield or
# explicitly approved rebuild scenarios.

resource "nutanix_virtual_machine_v2" "planned" {
  for_each = var.enable_vm_creation ? local.workloads : {}

  name                 = each.value.name
  description          = "Generated by Nutanix Migration Factory"
  num_sockets          = each.value.vcpu
  num_cores_per_socket = 1
  memory_size_bytes    = each.value.memory_size_bytes

  cluster {
    ext_id = var.cluster_ext_id
  }

  dynamic "nics" {
    for_each = each.value.target_network != "" ? [each.value.target_network] : []
    content {
      network_info {
        nic_type  = "NORMAL_NIC"
        vlan_mode = "ACCESS"

        subnet {
          ext_id = var.subnet_ext_ids[nics.value]
        }
      }
    }
  }

  lifecycle {
    precondition {
      condition     = each.value.target_network == "" || contains(keys(var.subnet_ext_ids), each.value.target_network)
      error_message = "Every non-empty target network must have a subnet_ext_ids mapping."
    }
  }
}
'''

    outputs_tf = '''output "planned_workloads" {
  description = "Workloads represented by this generated planning pack."
  value = local.workloads
}

output "created_vm_ext_ids" {
  description = "VM extIds only when enable_vm_creation=true."
  value = {
    for key, vm in nutanix_virtual_machine_v2.planned : key => vm.ext_id
  }
}
'''

    tfvars_example = '''nutanix_endpoint = "prism-central.example.com"
nutanix_port     = 9440
nutanix_insecure = false

# Prefer TF_VAR_nutanix_api_key in the shell rather than writing the key here.
# nutanix_api_key = "DO-NOT-COMMIT"

cluster_ext_id = "replace-with-authorized-cluster-ext-id"

subnet_ext_ids = {
  # "AHV-PROD-APP" = "replace-with-subnet-ext-id"
}

# Intentionally false. VMware migration workloads should normally be moved.
enable_vm_creation = false
'''

    readme = '''# Nutanix Migration Factory - Terraform Export

This archive is a reviewable Infrastructure-as-Code planning artifact generated
from the current Migration Factory estate. It is not proof that Terraform has
been applied to a Nutanix environment.

## Safety

- VM creation is disabled by default.
- VMware-to-AHV workloads should normally be migrated with Nutanix Move.
- No credentials or API keys are included.
- The pack does not infer boot disks, images, guest customization, storage
  containers, IP addresses, or application data.

## Review workflow

terraform init
terraform fmt -check
terraform validate
terraform plan -var-file=terraform.tfvars.example

Supply the API key via TF_VAR_nutanix_api_key and validate the provider/Prism
compatibility, cluster extId, subnet extIds, workload sizing and change record
before any approved apply.
'''

    inventory = json.dumps(
        {
            "workloads": list(workload_map.values()),
            "target_clusters": list(cluster_map.values()),
            "provenance": "Generated from operator-imported Migration Factory planning data.",
        },
        indent=2,
        sort_keys=True,
    )

    files = {
        "README.md": readme.encode(),
        "versions.tf": versions_tf.encode(),
        "provider.tf": provider_tf.encode(),
        "variables.tf": variables_tf.encode(),
        "locals.tf": locals_tf.encode(),
        "planned_vms.tf": planned_vms_tf.encode(),
        "outputs.tf": outputs_tf.encode(),
        "terraform.tfvars.example": tfvars_example.encode(),
        "inventory.json": inventory.encode(),
    }

    manifest = {
        name: {"sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data)}
        for name, data in sorted(files.items())
    }
    files["manifest.json"] = json.dumps(
        {
            "files": manifest,
            "notes": [
                "No secrets are included in this export.",
                "VM creation is disabled by default.",
                "Generated HCL must be validated against the authorized Nutanix environment before use.",
            ],
        },
        indent=2,
        sort_keys=True,
    ).encode()

    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, data in files.items():
            zf.writestr(name, data)
    return output.getvalue()